services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile.dev
    container_name: code-test-taskboard-api
    environment:
      API_PORT: "8080"
      DB_DRIVER: mysql
      DB_HOST: db
      DB_PORT: "3306"
      DB_NAME: code_test_taskboard
      DB_USER: app
      DB_PASSWORD: app
    restart: unless-stopped
    ports:
      - "8080:8080"

  db:
    image: mysql:8.1
    container_name: code-test-taskboard-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: code_test_taskboard
      MYSQL_USER: app
      MYSQL_PASSWORD: app
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./db/init:/docker-entrypoint-initdb.d

  adminer:
    image: adminer:4
    container_name: code-test-taskboard-adminer
    depends_on:
      - db
    ports:
      - "8081:8080"

  ui:
    build:
      context: ./ui
      dockerfile: Dockerfile.dev
    container_name: code-test-taskboard-ui
    depends_on:
      - api
    ports:
      - "4200:4200"
    restart: unless-stopped
    volumes:
      - ./ui:/app
      - /app/node_modules

volumes:
  db_data:
